local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set("n", "<leader>dd", builtin.diagnostics)
local function get_visual_selection()
    -- Yank visual selection into `v` register
    vim.cmd('noau normal! "vy"')
    return vim.fn.getreg('v')
end
vim.keymap.set('v', '<leader>ps', function()
    builtin.grep_string({ search = get_visual_selection() })
end)
vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})
